# Generated by Django 5.2.8 on 2025-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Продолжительность')),
                ('service_type', models.CharField(choices=[('PHOTO', 'Фотосъемка'), ('VIDEO', 'Видеосъемка'), ('EDITING', 'Обработка'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип услуги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная услуга')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'service_type', 'name'],
            },
        ),
    ]
