# Generated by Django 5.2.7 on 2025-12-02 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='can_be_booked',
            field=models.BooleanField(default=True, verbose_name='Можно забронировать'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_booking_hours',
            field=models.IntegerField(default=8, verbose_name='Максимальное время бронирования (часы)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_booking_hours',
            field=models.IntegerField(default=1, verbose_name='Минимальное время бронирования (часы)'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_time',
            field=models.IntegerField(default=1, verbose_name='Время на подготовку (часы)'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(verbose_name='Дата съемки')),
                ('booking_time', models.TimeField(verbose_name='Время съемки')),
                ('duration', models.IntegerField(default=2, verbose_name='Продолжительность (часы)')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Место съемки')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_message', models.TextField(blank=True, verbose_name='Пожелания и комментарии')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('price_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Согласованная цена')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_managed', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил администратор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['status'], name='gallery_app_status_d55cd6_idx'), models.Index(fields=['booking_date'], name='gallery_app_booking_9bb7fa_idx'), models.Index(fields=['user', 'status'], name='gallery_app_user_id_e02f7b_idx')],
            },
        ),
    ]
